{{- $storeName := include "secret-replicator.storeName" . }}
{{- range .Values.replications }}
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: {{ .name }}
  labels:
    {{- include "secret-replicator.labels" $ | nindent 4 }}
spec:
  externalSecretName: {{ default .name .externalSecretName }}
  refreshTime: {{ default "1m" .refreshTime }}
  {{- with .namespaceSelectors }}
  namespaceSelectors:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  externalSecretSpec:
    refreshInterval: {{ default "1m" .refreshInterval }}
    secretStoreRef:
      kind: ClusterSecretStore
      name: {{ $storeName }}
    target:
      name: {{ default .name .target.name }}
      {{- with .target.type }}
      template:
        type: {{ . }}
      {{- end }}
    dataFrom:
      - extract:
          key: {{ .source.key }}
{{- end }}
