{{- $storeName := .Values.store.name }}
{{- range .Values.secrets }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  refreshInterval: 30s
  secretStoreRef:
    kind: SecretStore
    name: {{ $storeName }}
  dataFrom:
    - extract:
        key: {{ .path }}
{{- end }}
