---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.store.name }}
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    vault:
      server: {{ .Values.store.server }}
      path: "secret"
      version: v2
      auth:
        tokenSecretRef:
          name: {{ .Values.store.auth.secretName }}
          key: token
