---
apiVersion: kafka.strimzi.io/v1
kind: KafkaConnect
metadata:
  name: {{ .Values.kafkaConnect.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  {{- if .Values.kafkaConnect.image }}
  image: {{ .Values.kafkaConnect.image }}
  {{- else }}
  version: {{ .Values.kafkaConnect.version }}
  {{- end }}
  replicas: {{ .Values.kafkaConnect.replicas }}
  bootstrapServers: {{ join "," .Values.kafka.brokers }}
  groupId: {{ .Values.kafkaConnect.name }}-connect
  configStorageTopic: {{ .Values.kafkaConnect.name }}-connect-configs
  offsetStorageTopic: {{ .Values.kafkaConnect.name }}-connect-offsets
  statusStorageTopic: {{ .Values.kafkaConnect.name }}-connect-status

  {{- if and .Values.kafkaConnect.build.enabled (not .Values.kafkaConnect.image) }}
  build:
    output:
      type: {{ .Values.kafkaConnect.build.output.type }}
      image: {{ .Values.kafkaConnect.build.output.image }}
      {{- with .Values.kafkaConnect.build.output.pushSecret }}
      pushSecret: {{ . }}
      {{- end }}
    {{- with .Values.kafkaConnect.build.plugins }}
    plugins:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}

  {{- if .Values.kafka.tls.enabled }}
  tls:
    trustedCertificates:
    - certificate: ca.crt
      secretName: {{ .Values.kafka.tls.secretName }}
  {{- end }}

  {{ if .Values.kafka.sasl.enabled }}
  authentication:
    type: {{ .Values.kafka.sasl.type }}
    username: ${secrets:{{ .Release.Namespace }}/{{ .Values.kafka.sasl.secretName }}:USERNAME}
    passwordSecret:
      secretName: {{ .Values.kafka.sasl.secretName }}
      password: PASSWORD
  {{ end }}
  config:
    config.providers: secrets,configmaps,env
    config.providers.configmaps.class: io.strimzi.kafka.KubernetesConfigMapConfigProvider
    config.providers.secrets.class: io.strimzi.kafka.KubernetesSecretConfigProvider
    config.providers.env.class: org.apache.kafka.common.config.provider.EnvVarConfigProvider
    {{- with .Values.kafkaConnect.config }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  template:
    serviceAccount:
      metadata:
        annotations:
          prometheus.io/port: "9094"
          prometheus.io/scrape: "true"
          prometheus.io/scrape_interval: 30s
    connectContainer:
      env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.kafka.sasl.secretName }}
              key: USERNAME
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.kafka.sasl.secretName }}
              key: PASSWORD
        - name: SASL_JAAS_CONFIG
          value: org.apache.kafka.common.security.scram.ScramLoginModule required username="$(USERNAME)" password="$(PASSWORD)";
