{{- if .Values.networkPolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-console-to-connect-api
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      strimzi.io/kind: KafkaConnect
      strimzi.io/cluster: {{ .Values.kafkaConnect.name }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Values.networkPolicy.consoleNamespace }}
      podSelector:
        matchLabels:
          {{- toYaml .Values.networkPolicy.consolePodLabels | nindent 10 }}
    ports:
      - protocol: TCP
        port: 8083
{{- end }}
