{{ $vaultAuthName := .Values.vaultAuth.name }}
{{- range .Values.secrets }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ .name }}
spec:
  refreshAfter: {{ default "30s" .refreshAfter }}
  vaultAuthRef: {{ $vaultAuthName }}
  type: kv-v2
  mount: secret
  path: {{ .path }}

  destination:
    name: {{ .destination }}
    create: true
    {{- if  .labels }}
    labels:
      {{- toYaml .labels | nindent 6 }}
    {{- end }}
    {{- if  .transformation }}
    transformation:
      {{- toYaml .transformation | nindent 6 }}
    {{- end }}
{{- end }}
