---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: {{ .Release.Name }}
  namespace: {{ $.Release.Namespace }}
spec:
  method: kubernetes
  mount: {{ .Values.auth.mount }}
  kubernetes:
    role: {{ .Values.auth.role }}
    serviceAccount: {{ include "vault-secret.serviceAccountName" . }}
    audiences: {{ toYaml .Values.auth.audiences | nindent 6 }}
