{{- range .Values.secrets }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  refreshAfter: {{ default "30s" .refreshAfter }}
  vaultAuthRef: {{ $.Release.Name }}
  type: kv-v2
  mount: secret
  path: {{ .path }}

  destination:
    create: true
    overwrite: {{ default false .overwrite }}
    name: {{ .name }}
    {{- with  .labels }}
    labels:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .annotations }}
    annotations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with  .transformation }}
    transformation:
      {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end }}
