---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: {{ .Values.vaultAuth.name }}
spec:
  method: kubernetes
  mount: {{ .Values.auth.mount }}
  kubernetes:
    role: {{ .Values.auth.role }}
    serviceAccount: default
    audiences:
      - vault
